apiVersion: apps/v1
kind: Deployment
metadata:
  name: arch-hw-6-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: arch-hw-6-app
  template:
    metadata:
      labels:
        app: arch-hw-6-app
    spec:
      containers:
        - name: otus-lesson-6
          image: "{{ .Values.image }}"
          ports:
            - name: web
              containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: "{{ .Values.externalPostgresql.postgresqlUrl }}"
            - name: SPRING_DATASOURCE_USERNAME
              value: {{ .Values.externalPostgresql.postgresqlUsername }}
            - name: SPRING_DATASOURCE_PASSWORD
              value: {{ .Values.externalPostgresql.postgresqlPassword }}