apiVersion: v1
kind: Service
metadata:
  name: arch-hw-6-service
spec:
  selector:
    app: arch-hw-6-app
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: web
  type: {{ .Values.service.type }}