replicaCount: 2

image: alexanderrodnin/otus-lesson-6:v1

service:
  type: NodePort
  port: 8080

externalPostgresql:
  postgresqlUsername: postgres
  postgresqlPassword: postgres
  postgresqlUrl: "jdbc:postgresql://pg-postgresql:5432/postgres"